name: booking_app_internship_algoriza
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: null
  carousel_slider: null

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: null
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: null
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  image_picker:
  smooth_page_indicator: null

dev_dependencies:
  auto_divider: ^1.0.0
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  material_floating_search_bar: ^0.3.7
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.1.0+1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/translation/ar-AR.json
    - assets/translation/en-EN.json
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
